### ISSUE TITLE
not working in ios 10.3.1 REAL DEVICE

### ISSUE THREAD

**Issue by luigi37** [abeauseigle/TodoApp#12]
Hi Alain,
everything worked fine in the last few years and it's still the case in

- ripple
- android emulator
- android real device
- ios simulator

On iOS real device (iPhone5) I cannot get any response (it seems since 10.3.1 update)...

Any idea?

Thanks

Luigi

**Comment by abeauseigle** [comment]
Hi Luigi,
I have no idea, I used it only on my Android cell to do my timesheet and expenses with Google Chrome.
May be you should investigate about the following factors.
- Is the browser version (on real device) support WebSQL?
- Is the memory allocation to WebSQL is too big? How big mem you allocated? More than 5Mb (DOMException https://dzone.com/articles/safari-ios-7-and-html5)?
- Did you tried another browser on iOS (Safari, Chrome, Opera, etc.)? Don't use OperaMini
- Is a special setting is required to allow WebSQL? (I brainstorm ;-))
- Is there a limit about the number of WebSQL app? Need a cleanup of all webSQL DB?
-Did you tried it to another iOS device using this update or greater one?
- On iOS 8 the localStorage is sometimes cleared when memory is low.

If you find the reason, it will be appreciated for the very little community. Ciao! :-)

Note: I consider, we were lucky until now to have browsers allowing WebSQL because W3C never get back on their decision about WebSQL deprecated decision. Until now, I consider IndexedDB didn't give its promised, didn't evolved. Am I wrong?

**Comment by luigi37** [comment]
Hi Alain
After many trials i found it: you must assign a timeout....
Specifically i ve put 300000 (5 min) and it works now.
It's a ios only thing and it came out recently...

I totally agree on indexed dB... i didn't notice a lot of movement and it looks like websql is still far more usefull...
Ciao :-)
Luigi

**Comment by luigi37** [comment]
> Note: I consider, we were lucky until now to have browsers allowing WebSQL because W3C never get back on their decision about WebSQL deprecated decision. Until now, I consider IndexedDB didn't give its promised, didn't evolved. Am I wrong?

Hi Alain, look at this

https://github.com/litehelpers/Cordova-sqlite-help/issues/18#issuecomment-295683693

It looks like we have a great alternative whatever it happens with iOS and Android...
